# Site settings
author: Dominic Carolan
title: Software Engineering From Zero to Hero
header-img: img/home-bg.png
email: dominiccarolan@gmail.com
copyright_name: Dominic Carolan
description: > # this means to ignore newlines until "baseurl:"
  A walkthrough my software engineering journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  domeazner

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
